# -*- coding: utf-8 -*-
"""dataframebasics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_jUlMHz-axmLerDCdRpo1LUnN-QywPa
"""

import pandas as pd
df = pd.read_csv('smaller_table.csv')
df

weather_data = [('2024-03-01', 50.1, 13.3, 'Snow'),
                ('2024-03-02', 44.3, 11.7, 'Sunny'),
                ('2024-03-03', 71.9, 6.7, 'Rain'),
                ('2024-03-04', 30.3, 5.1, 'Snow'),
                ('2024-03-05', 45.2, 13.3, 'Rain'),
                ('2024-03-06', 52.6, 5.5, 'Snow')]

import pandas as pd
df = pd.DataFrame(weather_data, columns=['day', 'temperature', 'windspeed', 'event'])
df

df.shape

df.head()

df.tail()

df[2:5]

df.columns

df.day

df['day']

df.temperature

df.temperature.max()

df['temperature'].min()

df['event'].describe()

df[df.temperature == df.temperature.max()]

df.day[df.temperature == df.temperature.max()]

