# -*- coding: utf-8 -*-
"""Pandas_Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnBBjK1M8sDRaAzebOwDOkEy3H3mqPYu
"""

import pandas as pd
df = pd.read_csv('weather_nyc.csv')
df

df['Temperature'].max()

df['EST'][df['VisibilityMiles']==5]

df['DewPoint'].mean()

