# -*- coding: utf-8 -*-
"""IntroductionPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18asHndAZfyJzxj7BOyDNQYvt5iXOZh9L
"""

import pandas as pd
df = pd.read_csv('weather_nyc.csv')
df

df.Temperature.max()

df['Temperature'].max()

df.EST[df.SeaLevelPressure<29.65]

df['EST'][df['SeaLevelPressure']< 29.65]

df.SeaLevelPressure.max()

df.SeaLevelPressure.min()

df.WindspeedMPH.mean()

df.EST[df.Temperature<=33.5]

