# -*- coding: utf-8 -*-
"""DataFramesPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MfKLEUnfiMWzrkm0oHR4k8hEFPLKIoZI
"""

import pandas as pd
df = pd.read_csv('smaller_table.csv')
df

df.Temperature.min()

df.Day[df.Event=='Snow']

df.Day[(df.Event=='Snow') & (df.Temperature == 50.1)]
# df[(df['Event'] == 'Snow') & (df['Temperature'] == 50.1)]

df.shape

df.head()

df.tail()

df.columns

df.df['Day']

df.Day

df['Day']

df[0:3]

df[df.Temperature == df.Temperature.max()]

