# -*- coding: utf-8 -*-
"""Weather_File.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13NhZBqSrqNUEdk7wE4kRUL-laO_RluoS
"""

import csv
import random
from datetime import datetime, timedelta

# Function to generate random weather data
def generate_weather_data(date):
    temperature = round(random.uniform(30, 80), 1)  # Temperature in Fahrenheit
    dew_point = round(random.uniform(20, 70), 1)  # Dew point in Fahrenheit
    humidity = random.randint(40, 80)  # Humidity in percentage
    sea_level_pressure = round(random.uniform(29.5, 30.5), 2)  # Sea level pressure in inches of mercury
    visibility_miles = random.randint(5, 10)  # Visibility in miles
    wind_speed_mph = round(random.uniform(5, 15), 1)  # Wind speed in miles per hour
    precipitation = round(random.uniform(0, 0.5), 2)  # Precipitation in inches
    return [date.strftime('%m/%d/%Y'), temperature, dew_point, humidity, sea_level_pressure, visibility_miles, wind_speed_mph, precipitation]

# Function to write data to CSV file
def write_to_csv(filename, data):
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['EST', 'Temperature', 'DewPoint', 'Humidity', 'SeaLevelPressure', 'VisibilityMiles', 'WindspeedMPH', 'Precipitation'])
        writer.writerows(data)

# Generating weather data for 30 days
weather_data = []
start_date = datetime.now().replace(day=1)  # Start from the beginning of current month
for i in range(30):
    weather_data.append(generate_weather_data(start_date + timedelta(days=i)))

# Writing data to CSV file
write_to_csv('weather_nyc.csv', weather_data)

import pandas as pd
df = pd.read_csv('weather_nyc.csv')
df